"""added quantity for recipe ingredients

Revision ID: 002
Revises: 001
Create Date: 2022-08-25 13:08:08.999361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredient', ['id'])
    op.create_unique_constraint(None, 'recipe', ['id'])
    op.add_column('recipe_ingredient', sa.Column('quantity', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'recipe_ingredient', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_ingredient', type_='unique')
    op.drop_column('recipe_ingredient', 'quantity')
    op.drop_constraint(None, 'recipe', type_='unique')
    op.drop_constraint(None, 'ingredient', type_='unique')
    # ### end Alembic commands ###
