"""recipe_ingredient_class_name_changed

Revision ID: 9e66f8ed0974
Revises: 002
Create Date: 2022-08-25 21:10:56.659357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e66f8ed0974'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipeingredient',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('recipe', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ingredient', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingredient'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('recipe_ingredient')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredient',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipe', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('ingredient', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingredient'], ['ingredient.id'], name='recipe_ingredient_ingredient_fkey'),
    sa.ForeignKeyConstraint(['recipe'], ['recipe.id'], name='recipe_ingredient_recipe_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipe_ingredient_pkey'),
    sa.UniqueConstraint('id', name='recipe_ingredient_id_key')
    )
    op.drop_table('recipeingredient')
    # ### end Alembic commands ###
