version : '3'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  recipe-server:
    image: recipe-server
    env_file:
      - .env
    ports:
      - 8080:8080
